### ISSUE TITLE
Exclude More than 1 Pattern

### ISSUE THREAD

**Issue by sdoward** [mendhak/gradle-crowdin-plugin#1]
Perhaps I wasn't using the plugin correct but I was not able to exclude files with more than 1 pattern. Is the plugin capable of this?

**Comment by mendhak** [comment]
It's basically a callthrough to Ant's `copy` command, which in turn uses [`fileset`](http://ant.apache.org/manual/Types/fileset.html).  For some reason this one takes a space or comma separated list instead of an array.  

Try this

```
excludePattern = '**/*.txt, **/*.jpg, **/*.mov'
```

**Comment by sdoward** [comment]
Again it's probably due to lack of knowledge but how would I remap the following

`values-es-ES`

to

`values-es`

**Comment by mendhak** [comment]
You'd do that in the renameMapping, something like

```
renameMapping = [
        from: '^values-([^-]*)-([^-]*)/(.*)$',
        to  : /values-\1\/\3/
]
```

---

Btw, don't you mean the opposite?  Android language resource folders should be like `values-es-rES` or `values-af`.

I had to do that recently, see this:

https://github.com/mendhak/gpslogger/blob/master/gpslogger/build.gradle#L198-L226

**Comment by sdoward** [comment]
No we don't translate locales as well, it is only language specific at the moment. So values-LANGUAGECODE is fine. But crowdin always appends the locale. I have sent a small PR which updates the readme for devs like me. 

Unfortunately the renameMapping you provided doesn't download anything. Perhaps the plugin should throw an error if it can't complete.
